apiVersion: apps/v1
kind: Deployment
metadata:
  name: greetings-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greetings-project
  template:
    metadata:
      labels:
        app: greetings-project
    spec:
      containers:
      - name: greetings-project
        image: abqari63/greetings:latest
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: greetings-project
spec:
  type: NodePort
  selector:
    app: greetings-project
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
